[project]
name = "CuMind"
version = "0.1.95"
description = "A JAX-based CuMind is a JAX-based RL framework inspired by Google DeepMind. Achieve's superhuman performance in complex domains without pretraining nor prior knowledge of their rules."
readme = "README.md"
requires-python = ">=3.12"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
main = [
    "numpy>=2.3.0",
    "gymnasium>=1.1.1",
    "pygame>=2.6.1",
    "tqdm>=4.67.1",
    "jax>=0.6.2",       # Uses CPU by default; see config.py:385 for device selection.
    "flax>=0.10.6",
    "optax>=0.2.5",
    "chex>=0.1.89",
    "wandb>=0.20.1",
]
dev = [
    "ruff>=0.11.13",
    "pytest>=8.4.0",
    "mypy>=1.16.0",
    "ipython>=9.3.0",
    "ipykernel>=6.29.5",
    "pydeps>=3.0.1",
]

[tool.ruff]
line-length = 320
target-version = "py312"

[tool.ruff.lint]
select = [
    "E", # pycodestyle errors
    "F", # pyflakes errors
    "I", # isort checks
    "N", # pep8-naming
    "W", # warnings
]
ignore = ["E501"] # Ignore line length errors

[tool.mypy]
python_version = "3.12"
strict = true
warn_return_any = true
warn_unused_configs = true

[tool.uv]
default-groups = ["main", "dev"]
